projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: src/generated/postgraphile.graphql
    extensions:
      endpoints:
        default: http://localhost:5000/graphql
